import { useState } from "react";
import type { CSSProperties } from "react";
import { Calculator, ChevronDown, Clock3, Database, History, Pi, ArrowLeftRight } from "lucide-react";

type Mode = "DEG" | "RAD";
const sciRows = [["sin", "cos", "tan", "sin⁻¹", "cos⁻¹", "tan⁻¹"], ["sinh", "cosh", "tanh", "eˣ", "10ˣ", "ln"], ["log", "√", "∛", "xʸ", "1/x", "|x|"], ["π", "e", "(", ")", ",", "⌫"]];
const numberRows = [["7", "8", "9", "÷", "%", "AC"], ["4", "5", "6", "×", "+/−", "="], ["1", "2", "3", "−"], ["0", ".", "EXP", "+"]];

function evaluate(raw: string, mode: Mode) {
  let expression = raw.replace(/×/g, "*").replace(/÷/g, "/").replace(/−/g, "-").replace(/π/g, "Math.PI").replace(/\be\b/g, "Math.E").replace(/\^/g, "**");
  expression = expression.replace(/sin\(/g, mode === "DEG" ? "Math.sin((Math.PI/180)*" : "Math.sin(").replace(/cos\(/g, mode === "DEG" ? "Math.cos((Math.PI/180)*" : "Math.cos(").replace(/tan\(/g, mode === "DEG" ? "Math.tan((Math.PI/180)*" : "Math.tan(");
  expression = expression.replace(/sqrt\(/g, "Math.sqrt(").replace(/log\(/g, "Math.log10(").replace(/ln\(/g, "Math.log(");
  if (!/^[0-9+*/().,%\-\sA-Za-z_]+$/.test(expression) || /(?:constructor|window|document|globalThis|import|=>)/.test(expression)) throw new Error("입력을 확인하세요");
  const value = Function(`"use strict"; return (${expression})`)();
  if (typeof value !== "number" || !Number.isFinite(value)) throw new Error("계산할 수 없습니다");
  return Number(value.toFixed(10));
}

export default function CalculatorPanel() {
  const [expression, setExpression] = useState(""); const [display, setDisplay] = useState("0"); const [mode, setMode] = useState<Mode>("DEG"); const [memory, setMemory] = useState<number[]>([]); const [history, setHistory] = useState<string[]>(["log(1000) = 3", "cos(π) = -1"]); const [error, setError] = useState("");
  const append = (value: string) => { setError(""); setExpression(p => p + value); setDisplay(p => p === "0" ? value : p + value); };
  const clear = () => { setExpression(""); setDisplay("0"); setError(""); };
  const calculate = () => { try { const value = evaluate(expression || display, mode); const line = `${expression || display} = ${value}`; setDisplay(String(value)); setExpression(String(value)); setHistory(p => [line, ...p.filter(x => x !== line)].slice(0, 20)); } catch (e) { setError(e instanceof Error ? e.message : "계산할 수 없습니다"); } };
  const scientific = (key: string) => { if (key === "⌫") { setExpression(p => p.slice(0, -1)); setDisplay(p => p.length <= 1 ? "0" : p.slice(0, -1)); return; } const map: Record<string, string> = { sin: "sin(", cos: "cos(", tan: "tan(", sinh: "sinh(", cosh: "cosh(", tanh: "tanh(", "eˣ": "e^(", "10ˣ": "10^(", ln: "ln(", log: "log(", "√": "sqrt(", "∛": "sqrt(", "xʸ": "^(", "1/x": "1/(", "|x|": "abs(" }; append(map[key] ?? key); };
  const memoryAction = (action: string) => { const value = Number(display); if (action === "MC") setMemory([]); else if (action === "M+") setMemory(p => [...p, value]); else if (action === "M-") setMemory(p => [...p, -value]); else if (action === "MR" && memory[0] !== undefined) { setDisplay(String(memory[0])); setExpression(String(memory[0])); } };
  return <section className="card" style={{ maxWidth: 920, margin: "0 auto", padding: 24 }}><header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }}><div style={{ display: "flex", alignItems: "center", gap: 10 }}><Calculator size={24} color="#0f766e"/><h2 style={{ margin: 0 }}>과학 계산기</h2></div><button className="btn ghost" onClick={() => setMode(mode === "DEG" ? "RAD" : "DEG")}>{mode} <ChevronDown size={16}/></button></header><div style={{ display: "grid", gridTemplateColumns: "minmax(0, 1fr) 250px", gap: 20 }}><div><div style={{ background: "#dff5f0", borderRadius: 14, padding: "22px 24px", minHeight: 96, textAlign: "right", marginBottom: 12 }}><div style={{ color: "#64748b", minHeight: 24 }}>{expression || "수식을 입력하세요"}</div><strong style={{ display: "block", fontSize: 42, lineHeight: 1.1, overflowWrap: "anywhere" }}>{display}</strong>{error && <small style={{ color: "#b91c1c" }}>{error}</small>}</div><div style={{ display: "flex", gap: 8, marginBottom: 12, flexWrap: "wrap" }}>{["M+", "M-", "MR", "MC"].map(k => <button key={k} className="btn ghost" onClick={() => memoryAction(k)}>{k}</button>)}<span style={{ color: "#64748b", alignSelf: "center", fontSize: 13 }}><Database size={14}/> {memory.length}개 메모리</span></div><div style={{ display: "grid", gridTemplateColumns: "repeat(6, minmax(44px, 1fr))", gap: 8, marginBottom: 8 }}>{sciRows.flat().map(k => <button key={k} onClick={() => scientific(k)} style={keyStyle}>{k}</button>)}</div><div style={{ display: "grid", gridTemplateColumns: "repeat(6, minmax(44px, 1fr))", gap: 8 }}>{numberRows.flatMap((row, ri) => row.map(k => <button key={`${ri}-${k}`} onClick={() => k === "AC" ? clear() : k === "=" ? calculate() : append(k)} style={{ ...keyStyle, ...(k === "=" ? { background: "#34b992", color: "white" } : ["+", "−", "×", "÷", "%"].includes(k) ? { background: "#eef0ff", color: "#4f46e5" } : k === "AC" ? { background: "#fee2e2", color: "#b91c1c" } : {}) }}>{k}</button>))}</div></div><aside style={{ borderLeft: "1px solid #e2e8f0", paddingLeft: 18 }}><div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}><History size={17}/><strong>계산 기록</strong></div>{history.map((item, i) => <div key={`${item}-${i}`} style={{ padding: "11px 0", borderBottom: "1px solid #e2e8f0", color: "#475569", fontSize: 14 }}>{item}</div>)}<div style={{ marginTop: 18, display: "grid", gap: 8, color: "#64748b", fontSize: 13 }}><span><Clock3 size={14}/> 최근 계산 자동 저장</span><span><Pi size={14}/> {mode} 모드</span><span><ArrowLeftRight size={14}/> 메모리 슬롯 {memory.length}</span></div></aside></div></section>;
}
const keyStyle: CSSProperties = { minHeight: 48, borderRadius: 10, border: "1px solid #dbe3ef", background: "#f8fafc", color: "#0f172a", fontSize: 16, fontWeight: 700, cursor: "pointer" };

